"""create users_info with roleenum

Revision ID: 2e758796481d
Revises: e871e9e107aa
Create Date: 2025-09-20 08:26:45.109068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e758796481d'
down_revision: Union[str, Sequence[str], None] = 'e871e9e107aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profile', 'pic')
    op.drop_column('users_profile', 'pic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profile', sa.Column('pic', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('teacher_profile', sa.Column('pic', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
