"""create users_info with roleenum

Revision ID: 39b72b026f45
Revises: 302157639c3e
Create Date: 2025-09-20 07:43:02.886234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39b72b026f45'
down_revision: Union[str, Sequence[str], None] = '302157639c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('type_sig', sa.String(), nullable=False))
    op.alter_column('users_info', 'password',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'password',
               existing_type=sa.String(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('users_info', 'type_sig')
    # ### end Alembic commands ###
