"""create users_info with roleenum

Revision ID: a52c95773ce9
Revises: 2e758796481d
Create Date: 2025-09-20 09:17:39.359276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52c95773ce9'
down_revision: Union[str, Sequence[str], None] = '2e758796481d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_profile', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users_profile', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_profile', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teacher_profile', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
