"""create otp table

Revision ID: b2ed780c7a3e
Revises: 18b3022d346f
Create Date: 2025-09-14 19:39:02.333918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ed780c7a3e'
down_revision: Union[str, Sequence[str], None] = '18b3022d346f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_index(op.f('ix_otp_user'), 'otp', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_user'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
