"""create the user_info table

Revision ID: e6d3fa910a3b
Revises: a193d5f09c47
Create Date: 2025-09-13 12:20:02.524259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6d3fa910a3b'
down_revision: Union[str, Sequence[str], None] = 'a193d5f09c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='role_enum'),
               type_=sa.Enum('ADMIN', 'USER', name='roleenum'),
               existing_nullable=False)
    op.alter_column('users_info', 'phone_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'phone_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_info', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='roleenum'),
               type_=postgresql.ENUM('ADMIN', 'USER', name='role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
